# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGuidePanel
                                 A QGIS plugin
 A convenient tool that makes it easy to perform frequently used QGIS actions such as map navigation, zooming, attribute editing, and basemap switching.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-09
        copyright            : (C) 2025 by 技術チーム合同会社／TechTeam Solutions LLC
        email                : info@techteam.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGuidePanel class from file QGuidePanel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .q_guide_panel import QGuidePanel
    return QGuidePanel(iface)
